### PR TITLE
completed functions to use open weather api and began...

### PR DESCRIPTION
**Pull request by BryanBorek**
functions to fetch musicbrainz api Also changed a couple of classes to ids in the html. 

There are some comments in the js with some instructions. I'm hoping you guys will be able to fill in some genres in each variable array from line 7-22. I put placeholder in each to test. 
For example replace ['this is where we put genres for rain'] on line 9 with something like ['blues' , 'emo' , 'shanty']

The music search function does run but is not set up properly to return any results yet. It will act as if you're searching an undefined term. I think thats why we need the mbid for each genre.

Sorry I cant make it to class today, I'll try to check slack as much as possible. Hit me up on there if something just isn't working and I'll see what I can do from my phone to help.

### CODE REVIEW

**Review by Acronym247 — COMMENTED** [review]
Looks good

**Review by Akhi2time — COMMENTED** [review]
Looks nice Bryan! Nice Work!

**Review by Akhi2time — COMMENTED** [review]
Nice Work!

**Review by Acronym247 — COMMENTED** [review]
Nice

**Comment by Akhi2time** [comment]
Looks Nice!

**Review by Acronym247 — APPROVED** [review]
Nice

**Pull request merged**
